=== coordinationdesk/auxiliary-data-gathering-service/adgs/applications/TlDaemon/conf/TaskTable.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v3.5 NT (http://www.xmlspy.com) by  () -->
<xsd:schema xmlns:xsd="http://www.w3.org/2000/10/XMLSchema" elementFormDefault="qualified">
	<xsd:element name="Task_Table">
		<xsd:annotation>
			<xsd:documentation>Processor Task Table</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="Processor_Name" type="xsd:string"/>
				<xsd:element name="Version" type="xsd:string"/>
				<xsd:element name="Test">
					<xsd:simpleType>
						<xsd:restriction base="xsd:string">
							<xsd:enumeration value="Yes"/>
							<xsd:enumeration value="No"/>
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:element>
				<xsd:element name="Min_Disk_Space">
					<xsd:complexType>
						<xsd:simpleContent>
							<xsd:extension base="xsd:positiveInteger">
								<xsd:attribute name="units" use="required" value="MB">
									<xsd:simpleType>
										<xsd:restriction base="xsd:string">
											<xsd:enumeration value="MB"/>
										</xsd:restriction>
									</xsd:simpleType>
								</xsd:attribute>
							</xsd:extension>
						</xsd:simpleContent>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="Max_Time">
					<xsd:complexType>
						<xsd:simpleContent>
							<xsd:extension base="xsd:positiveInteger">
								<xsd:attribute name="units" use="required" value="sec">
									<xsd:simpleType>
										<xsd:restriction base="xsd:string">
											<xsd:enumeration value="sec"/>
										</xsd:restriction>
									</xsd:simpleType>
								</xsd:attribute>
							</xsd:extension>
						</xsd:simpleContent>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="Private_Config">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="List_of_Cfg_Files">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="Cfg_File" maxOccurs="unbounded">
											<xsd:complexType>
												<xsd:sequence>
													<xsd:element name="Version" type="xsd:string"/>
													<xsd:element name="File_Name" type="xsd:string"/>
												</xsd:sequence>
											</xsd:complexType>
										</xsd:element>
									</xsd:sequence>
									<xsd:attribute name="count" type="xsd:positiveInteger" use="required"/>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="Default" type="xsd:nonNegativeInteger" default="0"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="List_of_Config_Spaces">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="Config_Space" type="xsd:token" maxOccurs="unbounded"/>
						</xsd:sequence>
						<xsd:attribute name="count" type="xsd:positiveInteger" use="required"/>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="List_of_Pools">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="Pool" maxOccurs="unbounded">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="Detached" type="xsd:boolean"/>
										<xsd:element name="Killing_Signal" type="xsd:int"/>
										<xsd:element name="List_of_Tasks">
											<xsd:complexType>
												<xsd:sequence>
													<xsd:element name="Task" maxOccurs="unbounded">
														<xsd:complexType>
															<xsd:sequence>
																<xsd:element name="Name" type="xsd:string"/>
																<xsd:element name="Version" type="xsd:string"/>
																<xsd:element name="Critical" type="xsd:boolean"/>
																<xsd:element name="Criticality_Level" default="1" nullable="true">
																	<xsd:simpleType>
																		<xsd:restriction base="xsd:unsignedShort">
																			<xsd:minExclusive value="0"/>
																		</xsd:restriction>
																	</xsd:simpleType>
																</xsd:element>
																<xsd:element name="File_Name" type="xsd:string"/>
																<xsd:element name="List_of_Inputs">
																	<xsd:complexType>
																		<xsd:sequence>
																			<xsd:element name="Input" minOccurs="0" maxOccurs="unbounded">
																				<xsd:complexType>
																					<xsd:sequence>
																						<xsd:element name="Mode">
																							<xsd:simpleType>
																								<xsd:restriction base="xsd:string">
																									<xsd:enumeration value="SISTEMATIC"/>
																									<xsd:enumeration value="NRT"/>
																									<xsd:enumeration value="REPROCESSING"/>
																									<xsd:enumeration value="ALWAYS"/>
																								</xsd:restriction>
																							</xsd:simpleType>
																						</xsd:element>
																						<xsd:element name="Mandatory" default="Yes">
																							<xsd:simpleType>
																								<xsd:restriction base="xsd:string">
																									<xsd:enumeration value="No"/>
																									<xsd:enumeration value="Yes"/>
																								</xsd:restriction>
																							</xsd:simpleType>
																						</xsd:element>
																						<xsd:element name="List_of_Alternatives">
																							<xsd:complexType>
																								<xsd:sequence>
																									<xsd:element name="Alternative" maxOccurs="unbounded">
																										<xsd:complexType>
																											<xsd:sequence>
																												<xsd:element name="Order" type="xsd:nonNegativeInteger"/>
																												<xsd:element name="Origin" default="Yes">
																													<xsd:simpleType>
																														<xsd:restriction base="xsd:string">
																															<xsd:enumeration value="DB"/>
																															<xsd:enumeration value="PROC"/>
																															<xsd:enumeration value="LOG"/>
																														</xsd:restriction>
																													</xsd:simpleType>
																												</xsd:element>
																												<xsd:element name="Retrieval_Mode" default="exact">
																													<xsd:simpleType>
																														<xsd:restriction base="xsd:token">
																															<xsd:whiteSpace value="collapse"/>
																															<xsd:enumeration value="ValCover"/>
																															<xsd:enumeration value="LatestValCover"/>
																															<xsd:enumeration value="ValIntersect"/>
																															<xsd:enumeration value="LatestValIntersect"/>
																															<xsd:enumeration value="LatestValidityClosest"/>
																														</xsd:restriction>
																													</xsd:simpleType>
																												</xsd:element>
																												<xsd:element name="T0" default="0">
																													<xsd:simpleType>
																														<xsd:restriction base="xsd:int">
																															<xsd:whiteSpace value="collapse"/>
																														</xsd:restriction>
																													</xsd:simpleType>
																												</xsd:element>
																												<xsd:element name="T1" default="0">
																													<xsd:simpleType>
																														<xsd:restriction base="xsd:int">
																															<xsd:whiteSpace value="collapse"/>
																														</xsd:restriction>
																													</xsd:simpleType>
																												</xsd:element>
																												<xsd:element name="File_Type" type="xsd:string"/>
																												<xs:element name="File_Class" type="xsd:string" minOccurs="0"/>
																												<xsd:element name="File_Name_Type">
																													<xsd:simpleType>
																														<xsd:restriction base="xsd:string">
																															<xsd:enumeration value="Physical"/>
																															<xsd:enumeration value="Logical"/>
																															<xsd:enumeration value="Stem"/>
																														</xsd:restriction>
																													</xsd:simpleType>
																												</xsd:element>
																												<xs:element name="Stream" type="xs:boolean" minOccurs="0"/>
																												<xs:element name="FilterBySatellite" type="xs:boolean" minOccurs="0"/>
																												<xs:element name="FilterByMission" type="xs:boolean" minOccurs="0"/>
																											</xsd:sequence>
																										</xsd:complexType>
																									</xsd:element>
																								</xsd:sequence>
																								<xsd:attribute name="count" type="xsd:positiveInteger" use="required"/>
																							</xsd:complexType>
																						</xsd:element>
																					</xsd:sequence>
																				</xsd:complexType>
																			</xsd:element>
																		</xsd:sequence>
																		<xsd:attribute name="count" type="xsd:positiveInteger" use="required"/>
																	</xsd:complexType>
																</xsd:element>
																<xsd:element name="List_of_Outputs">
																	<xsd:complexType>
																		<xsd:sequence>
																			<xsd:element name="Output" minOccurs="0" maxOccurs="unbounded">
																				<xsd:complexType>
																					<xsd:sequence>
																						<xsd:element name="Destination" default="Yes">
																							<xsd:simpleType>
																								<xsd:restriction base="xsd:string">
																									<xsd:enumeration value="DB"/>
																									<xsd:enumeration value="PROC"/>
																								</xsd:restriction>
																							</xsd:simpleType>
																						</xsd:element>
																						<xsd:element name="Mandatory" default="Yes">
																							<xsd:simpleType>
																								<xsd:restriction base="xsd:string">
																									<xsd:enumeration value="No"/>
																									<xsd:enumeration value="Yes"/>
																								</xsd:restriction>
																							</xsd:simpleType>
																						</xsd:element>
																						<xsd:element name="File_Type" type="xsd:string"/>
																						<xsd:element name="File_Name_Type">
																							<xsd:simpleType>
																								<xsd:restriction base="xsd:string">
																									<xsd:enumeration value="Physical"/>
																									<xsd:enumeration value="Logical"/>
																									<xsd:enumeration value="Stem"/>
																								</xsd:restriction>
																							</xsd:simpleType>
																						</xsd:element>
																					</xsd:sequence>
																				</xsd:complexType>
																			</xsd:element>
																		</xsd:sequence>
																		<xsd:attribute name="count" type="xsd:positiveInteger" use="required"/>
																	</xsd:complexType>
																</xsd:element>
																<xsd:element name="List_of_Breakpoints">
																	<xsd:complexType>
																		<xsd:sequence>
																			<xsd:element name="Breakpoint" minOccurs="0" maxOccurs="unbounded">
																				<xsd:simpleType>
																					<xsd:restriction base="xsd:token">
																						<xsd:whiteSpace value="collapse"/>
																					</xsd:restriction>
																				</xsd:simpleType>
																			</xsd:element>
																		</xsd:sequence>
																		<xsd:attribute name="count" type="xsd:positiveInteger" use="required"/>
																	</xsd:complexType>
																</xsd:element>
															</xsd:sequence>
														</xsd:complexType>
													</xsd:element>
												</xsd:sequence>
												<xsd:attribute name="count" type="xsd:positiveInteger" use="required"/>
											</xsd:complexType>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
						<xsd:attribute name="count" type="xsd:positiveInteger" use="required"/>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== coordinationdesk/auxiliary-data-gathering-service/adgs/common_ADGS/ADGSConf/taskTables/ecmwfReception.xml
<Task_Table xmlns:a="http://www.acsys.it/schemas/IPF" xmlns:xsi="http://www.w3.org/2000/10/XMLSchema-instance" xsi:schemaLocation="http://www.acsys.it/schemas/IPF TaskTable.xsd">
	<Processor_Name>ECMWF_RECEPTION</Processor_Name>
	<Version>1.0</Version>
	<Test>No</Test>
	<Min_Disk_Space units="MB">1024</Min_Disk_Space>
	<Max_Time units="sec">0<!--no time limit for execution-->
	</Max_Time>
	<Private_Config>
		<List_of_Cfg_Files count="0">
		</List_of_Cfg_Files>
		<Default>0</Default>
	</Private_Config>
	<List_of_Config_Spaces count="0">
	</List_of_Config_Spaces>
	<List_of_Pools count="2">
		<Pool>
			<Detached>false</Detached>
			<Killing_Signal>15</Killing_Signal>
			<List_of_Tasks count="1">
				<Task>
					<Name>RENAMEINPUTFILE</Name>
					<Version>01.00</Version>
					<Critical>true</Critical>
					<Criticality_Level>1</Criticality_Level>
					<File_Name>/usr/local/components/ADGS/bin/RenameECMWFFile.sh</File_Name>
					<List_of_Inputs count="0">
					</List_of_Inputs>
					<List_of_Outputs count="0"/>
					<List_of_Breakpoints count="0"/>
				</Task>
			</List_of_Tasks>
		</Pool>
		<Pool>
			<Detached>false</Detached>
			<Killing_Signal>15</Killing_Signal>
			<List_of_Tasks count="1">
				<Task>
					<Name>S3ECMWFDFormatter</Name>
					<Version>01.00</Version>
					<Critical>true</Critical>
					<Criticality_Level>1</Criticality_Level>
					<File_Name>/usr/local/components/ADGS/bin/s2_ECMWF_re_formatter_task.rb</File_Name>
					<List_of_Parameters count="1">
						<Parameter mandatory="true">
							<Value>/data/ADGS/conf/s2_ecmwfd_reformatter.conf</Value>
						</Parameter>
					</List_of_Parameters>
					<List_of_Inputs count="0">
					</List_of_Inputs>
					<List_of_Outputs count="0"/>
					<List_of_Breakpoints count="0"/>
				</Task>
			</List_of_Tasks>
		</Pool>
	</List_of_Pools>
</Task_Table>

=== coordinationdesk/auxiliary-data-gathering-service/adgs/applications/TlDaemon/conf/TaskTable.SIR2LRC1.1.xml
<!-- edited with XML Spy v3.5 NT (http://www.xmlspy.com) by  () -->
<Task_Table xmlns:a="http://www.acsys.it/schemas/IPF" xmlns:xsi="http://www.w3.org/2000/10/XMLSchema-instance" xsi:schemaLocation="http://www.acsys.it/schemas/IPF TaskTable.xsd">
	<Processor_Name>SIR2LRC1</Processor_Name>
	<Version>1.0</Version>
	<Test>No</Test>
	<Min_Disk_Space units="MB">1024</Min_Disk_Space>
	<Max_Time units="sec">0</Max_Time>
	<Private_Config>
		<List_of_Cfg_Files count="1">
			<Cfg_File>
				<Version>1.0</Version>
				<File_Name>/usr/acs/processors/ipf1Va2.0/processors/config_files/CS_TEST_PCONF_PAR20040101_000000_20041231_000000_0001.XML</File_Name>
			</Cfg_File>
		</List_of_Cfg_Files>
		<Default>0</Default>
	</Private_Config>
	<List_of_Config_Spaces count="1">
		<Config_Space>Geophysical_Constants</Config_Space>
	</List_of_Config_Spaces>
	<List_of_Pools count="2">
		<Pool>
			<Detached>false</Detached>
			<Killing_Signal>15</Killing_Signal>
			<List_of_Tasks count="1">
				<Task>
					<Name>IPF1_SIR2_CAL1_STUB</Name>
					<Version>1.0</Version>
					<Critical>true</Critical>
					<Criticality_Level>1</Criticality_Level>
					<File_Name>/usr/acs/bin/ipf1_cal_stub</File_Name>
					<List_of_Inputs count="5">
						<Input>
							<Mode>ALWAYS</Mode>
							<Mandatory>Yes</Mandatory>
							<List_of_Alternatives count="1">
								<Alternative>
									<Order>0</Order>
									<Origin>DB</Origin>
									<Retrieval_Mode>ValCover</Retrieval_Mode>
									<T0>0</T0>
									<T1>0</T1>
									<File_Type>SIR2LRC10_</File_Type>
									<File_Name_Type>Physical</File_Name_Type>
								</Alternative>
							</List_of_Alternatives>
						</Input>
						<Input>
							<Mode>NRT</Mode>
							<Mandatory>Yes</Mandatory>
							<List_of_Alternatives count="2">
								<Alternative>
									<Order>0</Order>
									<Origin>DB</Origin>
									<Retrieval_Mode>LatestValCover</Retrieval_Mode>
									<T0>0</T0>
									<T1>0</T1>
									<File_Type>DOR_NAV_0_</File_Type>
									<File_Name_Type>Physical</File_Name_Type>
								</Alternative>
								<Alternative>
									<Order>1</Order>
									<Origin>DB</Origin>
									<Retrieval_Mode>LatestValCover</Retrieval_Mode>
									<T0>0</T0>
									<T1>0</T1>
									<File_Type>MPL_ORBPRE</File_Type>
									<File_Name_Type>Physical</File_Name_Type>
								</Alternative>
							</List_of_Alternatives>
						</Input>
						<Input>
							<Mode>SISTEMATIC</Mode>
							<Mandatory>Yes</Mandatory>
							<List_of_Alternatives count="1">
								<Alternative>
									<Order>0</Order>
									<Origin>DB</Origin>
									<Retrieval_Mode>LatestValCover</Retrieval_Mode>
									<T0>0</T0>
									<T1>0</T1>
									<File_Type>AUX_ORBDOR</File_Type>
									<File_Name_Type>Physical</File_Name_Type>
								</Alternative>
							</List_of_Alternatives>
						</Input>
						<Input>
							<Mode>REPROCESSING</Mode>
							<Mandatory>Yes</Mandatory>
							<List_of_Alternatives count="1">
								<Alternative>
									<Order>0</Order>
									<Origin>DB</Origin>
									<Retrieval_Mode>LatestValCover</Retrieval_Mode>
									<T0>0</T0>
									<T1>0</T1>
									<File_Type>AUX_ORBDOR</File_Type>
									<File_Name_Type>Physical</File_Name_Type>
								</Alternative>
							</List_of_Alternatives>
						</Input>
						<Input>
							<Mode>ALWAYS</Mode>
							<Mandatory>Yes</Mandatory>
							<List_of_Alternatives count="1">
								<Alternative>
									<Order>0</Order>
									<Origin>DB</Origin>
									<Retrieval_Mode>LatestValIntersect</Retrieval_Mode>
									<T0>0</T0>
									<T1>0</T1>
									<File_Type>IPF_DBASE_</File_Type>
									<File_Name_Type>Physical</File_Name_Type>
								</Alternative>
							</List_of_Alternatives>
						</Input>
						<Input>
							<Mode>ALWAYS</Mode>
							<Mandatory>Yes</Mandatory>
							<List_of_Alternatives count="1">
								<Alternative>
									<Order>0</Order>
									<Origin>DB</Origin>
									<Retrieval_Mode>LatestValCover</Retrieval_Mode>
									<T0>0</T0>
									<T1>0</T1>
									<File_Type>MPL_ORBPRE</File_Type>
									<File_Name_Type>Physical</File_Name_Type>
								</Alternative>
							</List_of_Alternatives>
						</Input>
					</List_of_Inputs>
					<List_of_Outputs count="0"/>
					<List_of_Breakpoints count="0"/>
				</Task>
			</List_of_Tasks>
		</Pool>
		<Pool>
			<Detached>false</Detached>
			<Killing_Signal>15</Killing_Signal>
			<List_of_Tasks count="1">
				<Task>
					<Name>INVENTORY</Name>
					<Version>1.0</Version>
					<Critical>true</Critical>
					<Criticality_Level>1</Criticality_Level>
					<File_Name>/usr/acs/bin/Inventory</File_Name>
					<List_of_Inputs count="0"/>
					<List_of_Outputs count="0"/>
					<List_of_Breakpoints count="0"/>
				</Task>
			</List_of_Tasks>
		</Pool>
	</List_of_Pools>
</Task_Table>

=== coordinationdesk/auxiliary-data-gathering-service/adgs/common_ADGS/ADGSConf/taskTables/kmlzipDistribFormat.xml
<Task_Table xmlns:a="http://www.acsys.it/schemas/IPF" xmlns:xsi="http://www.w3.org/2000/10/XMLSchema-instance" xsi:schemaLocation="http://www.acsys.it/schemas/IPF TaskTable.xsd">
	<Processor_Name>KMLZIP_DISTRIB_FORMAT</Processor_Name>
	<Version>1.0</Version>
	<Test>No</Test>
	<Min_Disk_Space units="MB">1024</Min_Disk_Space>
	<Max_Time units="sec">0<!--no time limit for execution-->
	</Max_Time>
	<Private_Config>
		<List_of_Cfg_Files count="0">
		</List_of_Cfg_Files>
		<Default>0</Default>
	</Private_Config>
	<List_of_Config_Spaces count="0">
	</List_of_Config_Spaces>
	<List_of_Pools count="1">
		<Pool>
			<Detached>false</Detached>
			<Killing_Signal>15</Killing_Signal>
			<List_of_Tasks count="1">
				<Task>
					<Name>ZipOutputTask</Name>
					<Version>01.00</Version>
					<Critical>true</Critical>
					<Criticality_Level>1</Criticality_Level>
					<File_Name>/usr/local/components/ADGS/bin/PackageFmtEOFpackTask-KMLzip</File_Name>
					<List_of_Parameters count="0">
					</List_of_Parameters>
					<List_of_Inputs count="0">
					</List_of_Inputs>
					<List_of_Outputs count="0"/>
					<List_of_Breakpoints count="0"/>
				</Task>
			</List_of_Tasks>
		</Pool>
	</List_of_Pools>
</Task_Table>
